### ISSUE TITLE
[AWS]EC2またはECS＋EC2へのデプロイ

### ISSUE THREAD

**Issue by mori0120** [RecursionTeamA-2023-03/UMLGenerator#42]

**Comment by sora-uzu** [comment]
EC2にデプロイ済
```
インスタンスタイプ：t2.micro(無料枠)
EBS: 30GIB(無料枠)
IPアドレス：52.6.0.59 *Elastic IPで固定済
```

○残タスク
-DB
docker volumesの永続化
RDSの使用検討

-コンテナの運用
　ECS, ECRの使用検討
ECR : コンテナイメージ の保存。類似サービスdocker hub 
ECS : 複数のコンテナを統合して管理できる(コンテナオーケストレーション)。aws上でいい感じにdocker pull(ECRから)して、docker runしてくれる感じ。
https://zenn.dev/ryota_koba04/articles/c616c17d72603c

-CI/CD作成
現状は都度pullしてdocker-compose upする運用
下記使用検討
circle ci
github actions
aws code シリーズ

-IPアドレス
独自ドメインにする。Route53
→バックエンドのみならいらない

-負荷分散
 ELB
 コンテナ管理のサービスでできるか調査

-ネットワーク構成図作成
